# Regex docu: https://www.rsyslog.com/doc/configuration/property_replacer.html
# Attention: Don't test regex on recommended https://www.rsyslog.com/regex/ as engine can differ - so (.*?) non greedy operator doesnt
# work on e.g. rocky9 rsyslog - use [^;] for all chars but ";" to match until first occurence of ";"
# see https://heemayl.net/posts/regex-non-greedy-operation-without-non-greedy-operators/
# Use bash script on same operating system to test regex!

# IDEA: We could also reduce server load by letting user enable this on demand as debugging mode (checkbox in global config that when checked
# puts this file in /etc/rsyslog.d/ and restarts rsyslog)

# Template docu: https://www.rsyslog.com/doc/configuration/templates.html
# $template remoteTemplate,"%$year%-%$month%-%$day% %timegenerated:12:19:date-rfc3339% %syslogseverity-text% %HOSTNAME% %syslogtag%  %msg:0:500%\n"
# $template sipTemplate,"%$year%-%$month%-%$day% %timegenerated:12:19:date-rfc3339% %syslogseverity-text% %HOSTNAME% %syslogtag% %.fromto% %.status%  %.fromPhone% %.toPhone%\n"
$template remoteTemplate,"%timegenerated:date-rfc3164% %syslogseverity-text% %HOSTNAME% %syslogtag%  %msg:0:500%\n"
$template sipTemplate,"%timegenerated:date-rfc3164% %syslogseverity-text% %HOSTNAME% %syslogtag% %.fromto% %.status%  %.fromPhone% %.toPhone%\n"


# Just kept for reference - Template could also be written like this
# template(name="sipTestTemplate2" type="list") {
#     property(name="timegenerated" dateFormat="rfc3339" position.from="0" position.to="19") constant(value=" ")
#     property(name="syslogseverity-text") constant(value=" ")
#     property(name="hostname") constant(value=" ")
#     property(name="syslogtag") constant(value=" ")
#     property(name="msg" regex.expression="((from )([^<>]+))" regex.submatch="1" regex.type="ERE") constant(value="\n")
# }

ruleset(name="remote") {
    if $msg contains ">SIP " then {
        # Don't log spamming OPTIONS and its ACK messages
        if $msg contains "012OPTIONS sip" or $msg contains "Record-Route" then {
            stop
        }

        # Uncomment to log full messages for debugging
        # action(type="omfile" file="/var/log/remote-debug" template="remoteTemplate")

        # We could also extract the IPs only but then we need 2 regexes what should reduce performance
        set $.fromto = re_extract($msg, "(from )([^<>]+)", 0, 2, "");
	    # set $.from = re_extract($msg, "(from )(([0-9]{1,3}\\.){3}[0-9]{1,3})", 0, 2, 0);
	    # set $.to = re_extract($msg, "(to ([0-9]{1,3}\\.){3}[0-9]{1,3})", 0, 1, 0);

        set $.status = re_extract($msg, "(#012#012)([^#]+)", 0, 2, "");
        set $.fromPhone = re_extract($msg, "((From: )([^;]+))", 0, 1, "");
        set $.toPhone = re_extract($msg, "((To: )([^;#]+))", 0, 1, "");
        # These were the first tries that work on the regex tester but don't on rocky9 - kept for reference
        # set $.fromPhone = re_extract($msg, "(From: .*?)(;)", 0, 1, "");
        # set $.toPhone = re_extract($msg, "(To: .*?)(;)", 0, 1, "");

        action(type="omfile" file="/var/log/remote" template="sipTemplate")

        stop
    }

    # All not SIP messages
    if $msg contains "MEM-CONN-ERROR" then {
        stop
    }

    action(type="omfile" file="/var/log/remote" template="remoteTemplate")

    stop
}

module(load="imudp") # needs to be done just once
input(type="imudp" port="514" ruleset="remote")
