<?php

namespace App\Utilities;

use App\BaseModel;
use App\Http\Controllers\BaseViewController;
use Closure;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Fluent;
use Illuminate\Validation\Validator;

/**
 * A Utitlity class for drop-in support of dynamic form
 * fields models etc.
 * Form fields can be generated from saved json/array schema
 *
 * @see \Modules\Ticketsystem\Entities\Ticket
 * @see \Modules\Ticketsystem\Entities\TicketType
 *
 * @author Wali Razzaq
 */
class DynamicFormFields implements Htmlable
{
    protected ?array $fields = null;

    protected ?array $validationAttributes = null;

    protected ?array $rules = null;

    protected ?Validator $validator = null;

    /**
     * A callable which resolves to the schema array
     * with following structure
     *
     * [
     *  'key' => 'used to generate name of the input field',
     *  'name' => 'used a label for display',
     *  'type' => 'text|date|number|checkbox etc.',
     *  'help' => 'e.g help icon', #optional
     *  'required' => 'a boolean to explicitly make field nullable|required',
     *  'rules' => 'array of laravel validation rules', #optional
     * ]
     */
    protected ?Closure $schema = null;

    /**
     * Callback to hook into the generated field
     * and rules to make any runtime changes
     *
     * callback could expect following params in order
     * as Fluent & Collection objects
     *
     * $field # fluent representation of the form field
     * $item  # fluent object of raw schema of the field
     * $rules # collection of rules for the field in context
     */
    protected ?Closure $onFieldGenerated = null;

    /**
     * parameter/columnn name to wrap the
     * input field names
     *
     * e.g. <input name='custom_data[zip]' .../>
     */
    protected string $name = 'custom_data';

    /**
     * Column name to extract the schema array
     * from the schemable model passed
     * to the constructor of this class
     */
    protected string $schemaColumn = 'dynamic_fields';

    /**
     * Attributes that would be added to every
     * field generated by the builder
     */
    protected array $globalAttributes = [];

    /**
     * array|Model to fill the values of the
     * form fields from
     *
     * Model expects a json colunm casted
     * as array with same name as $this->name
     */
    protected array|BaseModel $fieldable = [];

    public function __construct(?BaseModel $schemable = null)
    {
        $this->schemable($schemable);
    }

    public function schemaColumn(string $column): static
    {
        $this->flushCached();
        $this->schemaColumn = $column;

        return $this;
    }

    public function name(string $column): static
    {
        $this->flushCached();
        $this->name = $column;

        return $this;
    }

    public function schemable(?BaseModel $schemable = null): static
    {
        $this->flushCached();
        $this->schema = fn () => data_get($schemable, $this->schemaColumn, []);

        return $this;
    }

    public function fieldable(array|BaseModel $fieldable): static
    {
        $this->flushCached();
        $this->fieldable = $fieldable;

        return $this;
    }

    public function globalAttributes(array $rules = [])
    {
        $this->flushCached();
        $this->globalAttributes = $rules;

        return $this;
    }

    public function schema(array|callable $schema)
    {
        $this->flushCached();
        $this->schema = is_callable($schema) ? $schema : fn () => $schema;

        return $this;
    }

    public function validator(?Validator $validator = null): static
    {
        $this->validator = $validator;
        $this->setCustomAttributesToValidator();

        return $this;
    }

    public function fields(): array
    {
        if (is_null($this->fields)) {
            $this->build();
        }

        return $this->fields ?? [];
    }

    public function rules(): array
    {
        if (is_null($this->rules)) {
            $this->build();
        }

        return $this->rules ?? [];
    }

    public function toHtml()
    {
        if (blank($this->fields())) {
            return '';
        }

        $model = is_array($this->fieldable) ? BaseModel::make([$this->name => $this->fieldable]) : $this->fieldable;
        $fields = BaseViewController::prepare_form_fields($this->fields(), $model);
        $fields = BaseViewController::add_html_string($fields);

        return collect($fields)->pluck('html')->flatten()->map(fn (Htmlable $html) => $html->toHtml())->implode(PHP_EOL);
    }

    protected function build(): static
    {
        $data = is_array($this->fieldable) ? $this->fieldable : data_get($this->fieldable, $this->name, []);
        $this->fields = collect(value($this->schema))
            ->mapInto(Fluent::class)
            ->reject(fn ($item) => empty($item->key)) // remove any item having no key
            ->map(function (Fluent $item) use ($data) {
                $rules = collect([$item->required ? 'required' : 'nullable'])
                    ->when($item->type == 'checkbox')->push('boolean')
                    ->merge($item->rules ?? []);

                $name = str("$this->name.$item->key");

                $field = fluent([
                    ...$this->globalAttributes,
                    'name' => (string) $name->bracketify(),
                    'form_type' => $item->type,
                    'description' => $item->name,
                    'help' => $item->help,
                    'value' => data_get($data, $item->key),
                ]);

                value($this->onFieldGenerated, $field, $item, $rules);

                $this->rules[(string) $name] = $rules->all();
                $this->validationAttributes[(string) $name] = $item->name;

                return $field->toArray();
            })->all();

        $this->setCustomAttributesToValidator();

        return $this;
    }

    protected function setCustomAttributesToValidator()
    {
        if (is_null($this->validator) || blank($this->validationAttributes)) {
            return;
        }

        $this->validator->addCustomAttributes($this->validationAttributes);
    }

    protected function flushCached()
    {
        $this->fields = $this->rules = null;
    }
}
